import type { Metadata } from "next";
import "./globals.css"
import { Inter as FontSans } from "next/font/google"

import { cn } from "@/lib/utils"
import { ThemeProvider } from "@/components/theme-provider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "relative h-screen font-sans w-screen bg-orange-950 overflow-hidden",
          fontSans.variable
        )}>
        <div className="back"></div>
        <div className="relative z-10 w-full h-full overflow-y-auto">{children}</div>
      </body>
    </html>
  );
}
